### ISSUE TITLE
Why is this a consult-* package?

### ISSUE THREAD

**Issue by minad** [Ladicle/consult-tramp#1]
Hi, I just came across your package and I looked into it! There is no need to use Consult here. Instead you could create a generic package without a dependency on Consult. Instead of `consult--read` use `completing-read`. You could name your package `tramp-completion`.

https://github.com/Ladicle/consult-tramp/blob/main/consult-tramp.el#L118

~~~ elisp
(completing-read "Tramp: " (tramp-completion--candidates))
~~~

**Comment by minad** [comment]
It seems that [counsel-tramp](https://github.com/masasam/emacs-counsel-tramp) also shouldn't depend on Ivy/Counsel. A `tramp-completion` package based on `completing-read` would work with both Vertico and Ivy.

Also [helm-tramp](https://github.com/masasam/emacs-helm-tramp/blob/master/helm-tramp.el) seems to share most code with counsel-tramp. The only difference is that there is an additional helm source, but besides that all of the three packages consult-tramp, counsel-tramp and helm-tramp could be a single package. If necessary it could provide a tiny bit of Helm-specific integration code (Helm actions, Helm sources).

**Comment by elken** [comment]
@minad Based on your feedback, I've begun a refactor of this package to better take advantage of consult features.

@Ladicle would these changes be well recieved here?

**Comment by minad** [comment]
@elken I think it would be better to create a single unified package which does not use Consult and which supersedes all three packages. But one could still provide improved Consult/Helm integration in eval-after-load blocks.

**Comment by elken** [comment]
I agree with you to a degree, but I'm not familiar enough with helm or ivy/counsel to use their internal APIs as effectively.

Seems like all 3 of these packages could be indeed merged under one roof, but this also seems like a conversation to take out of this :)

To answer the original point though; I have refactored the package to properly utilize consult, a PR of which should be up tomorrow sometime. If you're happy for me to, I can add a "fixes #1" in the commit and we can take this offline somewhere?

**Comment by Ladicle** [comment]
@elken I will gladly import it if you can fix it. It would be nice to be able to reduce dependencies using completing-read.

**Comment by minad** [comment]
@Ladicle To be clear I advocated for a generic non-Consult version based purely on completing-read. @elken takes the different route and rebuilds this package using Consult sources, which gives a lot of flexibility. Depends on your preferences which route to take. The downside of the Consult-specific implementation is that it is redundant with the other packages counsel-tramp and helm-tramp. The upside is that one can take advantage of additional Consult features.

Since this package is a rather small "integration package" it seems that a Consult-specific version is justified. To me it seems to be a good policy to avoid dependencies for "freestanding packages" (in contrast to "integration packages"), which provide a lot of functionality out of their own. Examples are dtache, devdocs or citar, which are all agnostic of the completion system. For dtache there exists a separate consult integration, dtache-consult. Citar can be contrasted with org-ref which has a large dependency footprint, which is better avoided.

**Comment by Ladicle** [comment]
@minad Thanks for your suggestion. I have read some of the other packages. I prefer the "freestanding packages" with "small integration package" style like dtache and flyspell-correct.

**Comment by minad** [comment]
I think @elken merged tramp support into consult-dir, such that this package is superseded and the issue can be closed?
